### ISSUE TITLE
[Dungeon] Dire Maul: North - Frost Trap

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/KurthosWoW.Trinitycore#9]
**Description:**

The Frost Trap used to freeze Guard Slip'kik in Dire Maul North is not working properly

**Current behaviour:**

When you set the Frost Trap he walks over it and it doesnt freeze him

**Expected behaviour:**

It should freeze Guard Slip'kik when he walks on top of it

**Steps to reproduce the problem:**

1. Go to Dire Maul North
2. Use a Thorium Widget and a Frost Oil to activate the trap
3. Complete the quest that the trap offers
4. Slip'kik disregards trap

**Comment by HelloKitty** [comment]
It seems to work? He walked over it and got frozen.


![](https://i.imgur.com/ZajcHdU.png)


Retest on the test realm, if it doesn't work in some cases then I need to know when/how. Closing for now.
